### ISSUE TITLE
Can't Read data (payload) from non-NDEF tag

### ISSUE THREAD

**Issue by BenCohenBenCohen** [don/phonegap-nfc-reader#14] opened 2015-04-27 08:55 UTC
Hi,
I'm trying to read from my non-NDEF NFC card.
the only ACTION that is triggered is ACTION_TAG_DISCOVERED and i only can read the tag_info.

the tag's techs are "NfcB" and "IsoDep"

can anyone please help me get the data?

**Comment by don** [comment] 2015-05-03 18:39
Duplicate of https://github.com/chariotsolutions/phonegap-nfc/issues/186

**Closed by don** 2015-05-03 18:39 UTC
